# Build Jekyll and Deploy to Github Pages
name: Jekyll site CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Ruby 셋업 전 Windows 종속성이 포함된 lock 파일 제거
    - name: 🗑️ Remove Gemfile.lock
      run: rm Gemfile.lock

    - name: 💎 Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true 

    - name: 👷 Build the site
      run: bundle exec jekyll build --future -d build
    
    - name: 🚀 Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build
