# Build Jekyll and Deploy to Github Pages
name: Jekyll site CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Node 버전 지원 종료 경고 해결

    - name: 💎 Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # 필요 시 프로젝트에 맞는 Ruby 버전으로 수정
        bundler-cache: true # 자동으로 bundle install을 실행하고 캐싱 처리함

    - name: 👷 Build the site
      run: bundle exec jekyll build --future -d build
    
    - name: 🚀 Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build
